# ***Broadcasting VS Vectorization***

1. Vectorization - performing operations on the entire array at once without using python loops
    
there are some benefits of using vectorization -

    1.   Eliminates the python loops
    2.   Reduce the Redundancy
    3.   much faster than the python loops
    4.   Increases the Readability of the code



2. Broadcasting - expands the smaller array into the same size of the greator arrray during the arithmetic operations
    
there are some benefits of using broadcasting -

    1.   Avoid Manual Reshaping
    2.   Avoid Memory Duplication
    3.   It will make the code simple & much smoother to understand




In [ ]:
import numpy as np

In [ ]:
# Vectorization -

arr1 = np.array([1,2,3,4])
arr2 = np.array([11,22,33,44])

arr = arr1 + arr2
# print(arr1)
# print(arr2)
print(arr)

[1 2 3 4]
[11 22 33 44]
[12 24 36 48]


In [ ]:
ary1 = np.array([30,48,57,76])
ary2 = np.array([39,83,75])

ary = ary1 + ary2
print(ary)

# in such scenarios when the smaller array is having more than one value, broadcasting won't work!
# it will only gonna work when the smaller array is a single value

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# broadcasting -

topSpeed = np.array([120, 150, 175, 230, 300])
lap = 5

finalTopSpeedListing = topSpeed * lap
print(finalTopSpeedListing)

# here, the magic of broadcasting has been implemented in which the smaller array (lap) is being expanded into [5,5,5,5,5] to achieve the final to speed list

[ 600  750  875 1150 1500]
