# *Random methods to generate a NumPy Array*



*   np.random.rand()    - will generate a +ve number (float) of numpy with the given range as well as it can also generate a numpy array on the basis of args
*   np.random.randn()   - will generate a random float value as well as random +ve or -ve array in numpy with the given range (can be +ve or -ve both)
*   np.random.randint() - it will generate a numpy array on the basis of the given range and args



In [24]:
import numpy as np

# # rand() -
# ranArr = np.random.rand()  # by default - 0 to 1
# print(ranArr)

# ranArr = np.random.rand() * 10  # it will generate a random value to 0 to 10
# print(ranArr)

# ranArr = np.random.rand(10) * 10  # it will generate a random value from 0 to 10 with the given args
# print(ranArr)


## randn() -
# ranArr = np.random.randn(5)
# print(ranArr)

# ranArr = np.random.randn(5,3)
# print(ranArr)

# ranArr = np.random.randn(2,3,5)
# print(ranArr)



## randInt() -
# randIntegerValue = np.random.randint(0, 10)
# print(randIntegerValue)

# ranArr = np.random.randint(1,10, size=[2,3])
# print(ranArr)

# ranArr = np.random.randint(1,10, size=[3, 4, 2])
# print(ranArr)

[[6 8 4]
 [2 5 9]]
[[[4 5]
  [3 3]
  [8 1]
  [4 4]]

 [[4 3]
  [6 1]
  [2 7]
  [6 5]]

 [[3 5]
  [4 7]
  [7 7]
  [3 9]]]


# **Vectorization in NumPy**

- performing some operations on entire array at once with out any python loops
- why we must use vectorization in NumPy?
  - Eliminated the python loops
  - uses optimized C-level implementations
  - Much Faster as compared to python loops
  - easy to understand (cleaner code hota hai!)
  - Increases the readability of the code

In [27]:
arr2 = np.array([1,2,3,4])
arr1 = np.array([10,20,30,40])

arr = arr1 - arr2
print(arr)

[ 9 18 27 36]


In [26]:
li1 = [1,2,3,4]
li2 = [10,20,30,40]
print(li1 + li2)

[1, 2, 3, 4, 10, 20, 30, 40]


In [28]:
arr = np.array([14,15,23,56,88,96])

arr1 = arr + 5
print(arr)
print(arr1)

[14 15 23 56 88 96]
[ 19  20  28  61  93 101]


In [ ]:
# arr = [10 20 30 40 50]      val = 5

# broadcasting - it will perform the operations b/w two or more than two arrays by extending the smaller value or array
# [10 20 30 40 50]        [5 5 5 5 5]