# **Flattening a NumPy Array**

In [16]:
# # Flateen Method to flat an array -
# import numpy as np

# arr = np.arange(1, 28)
# # print(arr)

# _2dArr = arr.reshape(3, 9)
# # print(_2dArr)

# _3dArr = arr.reshape(3,3,3)
# # print(_3dArr)

# flat2DArr = _2dArr.flatten()
# # print(flat2DArr)

# flat3DArr = _3dArr.flatten()
# # print(flat3DArr)



# # Ravel Method to flatten an array -
# rav2DArr = _2dArr.ravel()
# # print(rav2DArr)

# rav3DArr = _3dArr.ravel()
# # print(rav3DArr)

# # deep copy - value copy karo or sath me memory bhi copy karlo
# # shallow copy - value copy karo lekin memory copy mt karo


# # arr = np.array([[1,2,3,4],[5,6,7,8]])
# # print(arr)
# # flatArr = arr.flatten()
# # print(flatArr)

# # flatArr[0] = 10

# # print(arr)
# # print(flatArr)



# # ravArr = arr.ravel()
# # print(ravArr)

# # ravArr[0] = 110

# # print(arr)
# # print(ravArr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[110   2   3   4]
 [  5   6   7   8]]
[110   2   3   4   5   6   7   8]


## **Fancy Indexing**

In [20]:
import numpy as np

arr = np.arange(1, 11)
print(arr)

print(arr[0])
print(arr[2])
print(arr[4])
print(arr[6])

# fancy indexing -
print(arr[[0,2,4,6]])

[ 1  2  3  4  5  6  7  8  9 10]
1
3
5
7
[1 3 5 7]


# **Boolean Masking**

In [29]:
# to filter out the even elements of the given array we'll use boolean masking on the basis of certain condition I'll filter the even array
evenArr = arr[arr%2 == 0]
print(evenArr)

oddArr = arr[arr%2 != 0]
print(oddArr)

greatThan5 = arr[arr > 5]
smallTahn5 = arr[arr < 5]

print(greatThan5)
print(smallTahn5)


filteredArr = arr[(arr > 2) | (arr < 8)]    # &
print(filteredArr)

[ 2  4  6  8 10]
[1 3 5 7 9]
[ 6  7  8  9 10]
[1 2 3 4]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [35]:
ageArr = np.array([42,32,37,35,38,39,64,44])
print(ageArr)

is_any_person_greater_than_40 = (arr > 40).any()
print(is_any_person_greater_than_40)

is_any_person_greater_than_30 = (arr > 40).all()
print(is_any_person_greater_than_30)


[42 32 37 35 38 39 64 44]
False
False
