# **Methods to built a NumPy Array**

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,9])
print(arr)
np.ndim(arr)

[1 2 3 4 5 6 9]


1

**preparing 2D array in NumPy**

In [9]:
_2DArr = np.array([
    [10,20,30], [1,2,3]
])

print(_2DArr)
print(np.ndim(_2DArr))
print(np.shape(_2DArr))

[[10 20 30]
 [ 1  2  3]]
2
(2, 3)


***preparing 3D array in NumPy***

In [15]:
# _3DArr = np.array([
#     [10,20,30], [1,2,3], [4,5,6]
# ])

# print(_3DArr)
# print(np.ndim(_3DArr))
# print(np.shape(_3DArr))



_3DArr = np.array([[
    [10,20,30], [1,2,3], [4,5,6]
]])

print(_3DArr)
print(np.ndim(_3DArr))
print(np.shape(_3DArr))


_3DArr1 = np.array([
    [[10,20,30], [40,50,60]],
    [[1,2,3], [4,5,6]]
])

print(_3DArr1)
print(np.ndim(_3DArr1))
print(np.shape(_3DArr1))

[[[10 20 30]
  [ 1  2  3]
  [ 4  5  6]]]
3
(1, 3, 3)
[[[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]]
3
(2, 2, 3)


***Arange Method to build an NumPy array within a range***

In [22]:
# rangeArr = np.arange(startValue, endValue (end-1), skipValue)

rangeArr = np.arange(3, 101, 3)
print(rangeArr)

reverseArangeArr = np.arange(99, 0, -3)
print(reverseArangeArr)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[99 96 93 90 87 84 81 78 75 72 69 66 63 60 57 54 51 48 45 42 39 36 33 30
 27 24 21 18 15 12  9  6  3]


***Type-Casting in  NumPy Arrays***

In [36]:
arr = np.array([10,100,1000,10000])
print(arr)
print(arr.dtype)

int32Arr = np.array(arr, dtype=np.int16)
print(int32Arr)
print(int32Arr.dtype)

floatArr = np.array(arr, dtype=np.float64)
print(floatArr)
print(floatArr.dtype)

[   10   100  1000 10000]
int64
[   10   100  1000 10000]
int16
[   10.   100.  1000. 10000.]
float64


**LinSpace Method**

In [42]:
eqDivArr = np.linspace(0, 20, 5, dtype=np.int64)
print(eqDivArr)

[ 0  5 10 15 20]


**Reshape Method in NumPy**

In [52]:
_1DArr = np.arange(1, 37)
print(_1DArr)
print(np.ndim(_1DArr))

# Now, I am going to covert this linear array into a 2D-Array
# for this, we have to use reshape name ka method

_2DArr = _1DArr.reshape(2, 18)
print(_2DArr)

_2DArr = _1DArr.reshape(18, 2)
print(_2DArr)

_2DArr = _1DArr.reshape(6, 6)
print(_2DArr)

_2DArr = _1DArr.reshape(4, 9)
print(_2DArr)



# Alright! now we'll convert this _1DArr into _3DArr

_3DArr = _1DArr.reshape(2,2,9)   # page - 2  |  rows - 2  |  columns - 9
print(_3DArr)

_3DArr = _1DArr.reshape(2,3,6)   # page - 2  |  rows - 3  |  columns - 6
print(_3DArr)

_3DArr = _1DArr.reshape(6,2,3)   # page - 6  |  rows - 2  |  columns - 3
print(_3DArr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
1
[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]]

 [[19 20 21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34 35 36]]]
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]

 [[31 32 33]
  [34 35 36]]]
