# **Slicing a NumPy Array**

In [ ]:
li = [1,2,32,4,5,6]
# print(li)

# print(li[startIndex:endIndex])  # Slicing Syntax

print(li[1:4])

[2, 32, 4]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

arr1 = arr[:]
print(arr1)

arr1[0] = 11

print(arr)
print(arr1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[11  2  3  4  5  6]
[11  2  3  4  5  6]


In [ ]:
# numpy slicing in 2D-array -

arr = np.arange(1, 13).reshape(3, 4)
print(arr)

# arr[rows, columns]
# arr[startRowIndex:EndRowIndex, startColumnIndex:endColumnIndex]
print(arr[0:2, 0:2])
print(arr[:2, :2])

print(arr[1:, 2:])

print(arr[:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]
[[ 7  8]
 [11 12]]
[[2 3]
 [6 7]]


In [35]:
# 3D-array - slicing
arr = np.arange(1,13).reshape(2,2,3)

print(arr)

print(arr[:, 1:3,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 4  5  6]]

 [[10 11 12]]]
